bootJar {
    enabled = true
}

jar {
    enabled = false
}

repositories {
    mavenCentral()

}

dependencies {
    implementation(project(':daengle-domain'))
    implementation(project(':daengle-persistence-nosql')) // TODO 해당 의존성 걷어내야 함
    implementation(project(':daengle-auth'))

    implementation 'org.springframework.boot:spring-boot-starter-web'

    // websocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.webjars:stomp-websocket:2.3.4'

    // dynamo
    implementation platform('software.amazon.awssdk:bom:2.20.56')
    implementation 'software.amazon.awssdk:dynamodb'
    implementation 'software.amazon.awssdk:dynamodb-enhanced'

    // security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    testImplementation 'org.springframework.security:spring-security-test'

    // jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}

test {
    useJUnitPlatform()
}