rootProject.name = 'daengle-server'
include 'daengle-payment-api'
include 'daengle-domain'
include 'daengle-auth'
include 'daengle-persistence-rdb'
include 'daengle-user-api'
include 'daengle-groomer-api'
include 'daengle-vet-api'
include 'daengle-notification-api'
include 'daengle-chat-api'
include 'daengle-persistence-nosql'
include 'daengle-persistence-queue'

