bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    implementation(project(':daengle-domain'))
    implementation(project(':daengle-auth'))
    
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // solapi-kakao
    implementation 'net.nurigo:sdk:4.3.2'

    //Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Resilience4j
    implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.0.2'
    implementation 'io.github.resilience4j:resilience4j-timelimiter'

    //actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    //prometheus
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // AWS
    implementation platform("io.awspring.cloud:spring-cloud-aws-dependencies:3.0.1")
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-sqs:3.0.1'
}

